env:
- REPOSITORY_NAME=ip_print PACKAGE_NAME=main GENERATED_DEB_NAME=ip_print
language: cpp
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install qtbase5-dev qt5-default qttools5-dev libdbus-1-3 libxkbcommon-x11-0 xvfb gcc-7 g++-7 doxygen -y
script:
- mkdir -p build
- cd build
- cmake ../cmake
- cmake --build .
- make test
- cmake --build . --target package
- cd ..
- doxygen doxyfile.conf
- git clone https://boristestov:$GITHUB_TOKEN@github.com/boristestov/ip_print.github.io.git
- cd ip_print.github.io
- git rm -r *
- mv -v ../html/* .
- git add *
- git commit -m "Documentation from travis-ci build $TRAVIS_BUILD_NUMBER"
- git push https://boristestov:$GITHUB_TOKEN@github.com/boristestov/ip_print.github.io.git
- cd ..
- sudo rm -r ip_print.github.io
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T $GENERATED_DEB_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uboristestov:$BINTRAY_API_KEY "https://api.bintray.com/content/boristestov/$REPOSITORY_NAME/$PACKAGE_NAME/$TRAVIS_BUILD_NUMBER/$GENERATED_DEB_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

